### ISSUE TITLE
Explain how to install this

### ISSUE THREAD

**Issue by turion** [meraymond2/idris-vscode#44]
There is no installation instructions or links to a prebuilt `*.vsix`, it seems?

**Comment by michaelmesser** [comment]
You install it in VSCode. Type "Install Extensions" into the command palette. Search for "idris language". Make sure you install the one by meraymond.

**Comment by meraymond2** [comment]
Is there anything further you'd like me to detail in the readme? It mentions that you need to install Idris separately, but it's hidden somewhere in the middle. 

I could also add a section about installing and running it from the repo, since that can be useful for debugging.

Could probably also add the vsix files to the Github releases.

**Comment by turion** [comment]
I'd recommend simply linking to https://marketplace.visualstudio.com/items?itemName=meraymond.idris-vscode and pointing out that it's not the one by zjhmale.

**Comment by meraymond2** [comment]
I've updated the readme with some more thorough installation instructions.
