### ISSUE TITLE
RFC: borrow TM grammars to layer under semantic highlighting

### ISSUE THREAD

**Issue by dustypomerleau** [meraymond2/idris-vscode#5]
Thanks so much for working on this extension.

I am currently using your extension with the syntaxes from [vscode-idris](https://github.com/zjhmale/vscode-idris), which is working well. I know you have plans for semantic highlighting, but my experience with semantic highlighting has been that it often still needs a regex-based grammar to rely on for operators, punctuation, etc.

Perhaps you are planning to re-implement the regex-based grammars from scratch, but if you're interested in borrowing, the diff can be seen in this commit: https://github.com/dustypomerleau/idris-vscode/commit/02ff35d6d22dc91173dcfe6bb21e548ef0daedc5

**Comment by dustypomerleau** [comment]
Apologies, I should not have changed the path to the config file. Fixed with commit https://github.com/dustypomerleau/idris-vscode/commit/f7d6526dc0b123a9dcebba44e968fcd7a5dbcf13.

**Comment by meraymond2** [comment]
Hey, thanks for the issue :slightly_smiling_face:.

I agree that semantic highlighting will only be a supplement to regex-based highlighting. I doubt there's much benefit in trying to recreate those rules from scratch — that time would be better spent trying to get the semantic highlighting to work.

I had a quick look at the Atom grammar rules for comparison, and it turns out the vscode-idris rules are ported from the Atom plugin anyway, so I'm happy to borrow them too. I'll try to get a PR and a new version out with the improved grammar this week.

**Comment by dustypomerleau** [comment]
Thanks for spinning up the PR so quickly. I'm really looking forward to this hitting Marketplace. I've tweaked my [Yarra Valley](https://marketplace.visualstudio.com/items?itemName=dustypomerleau.yarra-valley) theme to work with these scopes.

**Comment by meraymond2** [comment]
It should be up now :+1:

**Comment by dustypomerleau** [comment]
Fantastic, thanks!
