### ISSUE TITLE
file path is wrong within workspace with multiple folders

### ISSUE THREAD

**Issue by locriacyber** [meraymond2/idris-vscode#70]
I have the following workspace with two folders:
![image](https://user-images.githubusercontent.com/74560659/138551763-80d19bdf-7dcf-4760-a4d2-fcd2ff3de9f7.png)

You can add a new folder to the current workspace like this
![image](https://user-images.githubusercontent.com/74560659/138551802-f5b0a68c-58ca-4afb-8d4b-6bf588ba3866.png)

The errors are shown in the "Problems" tab but not in the file editor (no squiggle underlines).
![image](https://user-images.githubusercontent.com/74560659/138551818-a5435b05-afa7-40e4-b746-d077182db9b8.png)

Note that the file path is `/null/...`, which is wrong.

**Comment by meraymond2** [comment]
I've had a look, I didn't reproduce the /null/ path bug, but I think I know what the problem is. The extension is just a translation layer between the Idris IDE process and VS, and currently it only ever launches a single Idris process. That IDE process needs to be launched in the app directory for the IDE commands to work, so to work with a multi-root workspace it would need to launch multiple processes, one per workspace-folder. 

That the logic to get the directory path is assuming a single workspace-folder is definitely a mistake, at the very least it should display an error to the user that it can't currently handle multi-root workspaces. Your change would make it work, but only for the first folder. 

For now, I'll document that it doesn't support multi-root workspaces, because the current behaviour is confusing and annoying. Longer term, I think launching multiple client processes could work, but I'm not sure how complicated it would be, so it might take a while.
